name: Get Cloudify Environment Data
author: Isaac Shabtay
description: Retrieves a Cloudify environment's data using name/labels or both, into a file and/or an output
branding:
  icon: cloud
  color: white
inputs:
  environment-name:
    description: Name of Cloudify environment to inquire
    required: false
  labels:
    description: |
      A labels list of the form <key>:<value>,<key>:<value>.
      Any comma and colon in <value> must be escaped with \.
      The labels’ keys are saved in lowercase.
    required: false
    default: "-"
  outputs-file:
    description: |
      Path to JSON file to receive the Cloudify environment's outputs
      and capabilities
    required: false
    default: "-"
outputs:
  environment-data:
    description: The Cloudify environment's outputs and capabilties
runs:
  using: docker
  image: docker://cloudifyplatform/cloudify-cli:6.3.0
  entrypoint: cfyci
  args:
    - get-environment-data-by-labels
    - '--name'
    - ${{ inputs.environment-name }}
    - '--labels'
    - ${{ inputs.labels }}
    - '--outputs-file'
    - ${{ inputs.outputs-file }}
